
#
# App Utilities for Pet Classifier, Similarity Search, and Painting Studio
#

from pathlib import Path
import numpy as np
import pandas as pd
import streamlit as st
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow import keras
from tensorflow.keras.applications import MobileNetV2, VGG19
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess_input
from tensorflow.keras.applications.vgg19 import preprocess_input as vgg_preprocess_input
from PIL import Image


#
# Project Paths and Constants
#

APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent

OUTPUT_DIR = PROJECT_ROOT / "outputs"
EMBEDDING_DIR = OUTPUT_DIR / "embeddings"
MODEL_DIR = OUTPUT_DIR / "models"
STYLE_DIR = PROJECT_ROOT / "assets" / "styles"

IMAGE_SIZE = (224, 224)
TOP_K_DEFAULT = 5
STYLE_MAX_DIM_DEFAULT = 256

STYLE_LAYERS = [
    "block1_conv1",
    "block2_conv1",
    "block3_conv1",
    "block4_conv1",
    "block5_conv1"
]

CONTENT_LAYERS = [
    "block5_conv2"
]


#
# Cached Loaders
#

@st.cache_data
def load_retrieval_metadata():
    """
    Load retrieval metadata generated by Notebook 04.
    """

    metadata_path = EMBEDDING_DIR / "04_pet_image_retrieval_metadata.csv"

    if not metadata_path.exists():
        raise FileNotFoundError(f"Missing retrieval metadata: {metadata_path}")

    return pd.read_csv(metadata_path)


@st.cache_data
def load_embeddings():
    """
    Load MobileNetV2 image embeddings generated by Notebook 04.
    """

    embeddings_path = EMBEDDING_DIR / "04_mobilenetv2_pet_image_embeddings.npy"

    if not embeddings_path.exists():
        raise FileNotFoundError(f"Missing embeddings file: {embeddings_path}")

    embeddings = np.load(embeddings_path)

    # Normalize embeddings so dot product is cosine similarity.
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
    norms = np.maximum(norms, 1e-12)

    normalized_embeddings = embeddings / norms

    return normalized_embeddings


@st.cache_data(ttl=60)
def load_style_image_paths():
    """
    Load available style image paths from assets/styles.

    The ttl setting lets the app refresh the style list periodically.
    """

    if not STYLE_DIR.exists():
        STYLE_DIR.mkdir(parents=True, exist_ok=True)

    style_paths = sorted(
        [
            path for path in STYLE_DIR.iterdir()
            if path.is_file() and path.suffix.lower() in [".jpg", ".jpeg", ".png"]
        ]
    )

    return style_paths


@st.cache_resource
def load_tfds_splits():
    """
    Load Oxford-IIIT Pet train and test splits.

    The retrieval corpus order is:
    1. train split,
    2. test split.
    """

    (ds_train_raw, ds_test_raw), ds_info = tfds.load(
        "oxford_iiit_pet",
        split=["train", "test"],
        as_supervised=False,
        with_info=True,
        shuffle_files=False
    )

    num_train = ds_info.splits["train"].num_examples
    num_test = ds_info.splits["test"].num_examples

    return ds_train_raw, ds_test_raw, ds_info, num_train, num_test


@st.cache_resource
def load_classifier_model():
    """
    Load the trained MobileNetV2 transfer learning classifier.
    """

    model_path = MODEL_DIR / "mobilenetv2_transfer_classifier.keras"

    if not model_path.exists():
        raise FileNotFoundError(f"Missing classifier model: {model_path}")

    model = keras.models.load_model(model_path, compile=False)

    return model


@st.cache_resource
def load_feature_extractor():
    """
    Load MobileNetV2 as an embedding feature extractor.
    """

    feature_extractor = MobileNetV2(
        input_shape=IMAGE_SIZE + (3,),
        include_top=False,
        weights="imagenet",
        pooling="avg"
    )

    feature_extractor.trainable = False

    return feature_extractor


#
# Species Filter Helpers
#

def infer_species_label_for_breed(metadata_df, breed_label):
    """
    Infer the species label associated with a predicted breed label.

    This is useful for uploaded images because the classifier predicts breed,
    while the retrieval filter can use species to avoid returning cats for dogs
    or dogs for cats.
    """

    subset = metadata_df.loc[metadata_df["breed_label"] == int(breed_label)]

    if subset.empty:
        return None

    return int(subset["species_label"].mode().iloc[0])


def get_allowed_retrieval_indexes(metadata_df, retrieval_filter="No filter", auto_species_label=None):
    """
    Return retrieval corpus indexes allowed by the selected species filter.

    Parameters
    ----------
    metadata_df : pd.DataFrame
        Retrieval metadata table.

    retrieval_filter : str
        One of "Auto", "Dog only", "Cat only", or "No filter".

    auto_species_label : int or None
        Species label to use when retrieval_filter is "Auto".

    Returns
    -------
    np.ndarray
        Array of allowed retrieval indexes.
    """

    if retrieval_filter == "No filter":
        return np.arange(len(metadata_df))

    if retrieval_filter == "Dog only":
        return metadata_df.index[metadata_df["species_name"].str.lower() == "dog"].to_numpy()

    if retrieval_filter == "Cat only":
        return metadata_df.index[metadata_df["species_name"].str.lower() == "cat"].to_numpy()

    if retrieval_filter == "Auto" and auto_species_label is not None:
        return metadata_df.index[metadata_df["species_label"] == int(auto_species_label)].to_numpy()

    # If auto filtering cannot be resolved, fall back to no filter.
    return np.arange(len(metadata_df))


#
# Retrieval Helpers
#

def retrieve_similar_images(
    query_index,
    normalized_embeddings,
    metadata_df,
    top_k=5,
    retrieval_filter="No filter",
    auto_species_label=None
):
    """
    Retrieve top-k similar dataset images for a selected dataset query index.
    """

    query_embedding = normalized_embeddings[int(query_index)]

    similarity_scores = normalized_embeddings @ query_embedding

    allowed_indexes = get_allowed_retrieval_indexes(
        metadata_df=metadata_df,
        retrieval_filter=retrieval_filter,
        auto_species_label=auto_species_label
    )

    # Mask out disallowed examples.
    masked_scores = np.full_like(similarity_scores, fill_value=-np.inf, dtype=np.float32)
    masked_scores[allowed_indexes] = similarity_scores[allowed_indexes]

    # Exclude the query image itself.
    masked_scores[int(query_index)] = -np.inf

    top_indexes = np.argsort(masked_scores)[::-1][:top_k]

    results_df = metadata_df.iloc[top_indexes].copy()
    results_df.insert(0, "retrieval_rank", range(1, len(top_indexes) + 1))
    results_df.insert(1, "retrieved_index", top_indexes)
    results_df.insert(2, "similarity_score", masked_scores[top_indexes])

    query_label = metadata_df.loc[int(query_index), "breed_label"]
    query_breed = metadata_df.loc[int(query_index), "breed_name"]

    results_df["query_index"] = int(query_index)
    results_df["query_breed_label"] = query_label
    results_df["query_breed_name"] = query_breed
    results_df["same_breed_as_query"] = results_df["breed_label"] == query_label

    return results_df


def retrieve_similar_images_from_embedding(
    query_embedding,
    normalized_embeddings,
    metadata_df,
    top_k=5,
    retrieval_filter="No filter",
    auto_species_label=None
):
    """
    Retrieve top-k similar dataset images for an uploaded image embedding.
    """

    query_embedding = query_embedding.reshape(1, -1)

    query_norm = np.linalg.norm(query_embedding, axis=1, keepdims=True)
    query_norm = np.maximum(query_norm, 1e-12)
    query_embedding = query_embedding / query_norm

    similarity_scores = normalized_embeddings @ query_embedding[0]

    allowed_indexes = get_allowed_retrieval_indexes(
        metadata_df=metadata_df,
        retrieval_filter=retrieval_filter,
        auto_species_label=auto_species_label
    )

    masked_scores = np.full_like(similarity_scores, fill_value=-np.inf, dtype=np.float32)
    masked_scores[allowed_indexes] = similarity_scores[allowed_indexes]

    top_indexes = np.argsort(masked_scores)[::-1][:top_k]

    results_df = metadata_df.iloc[top_indexes].copy()
    results_df.insert(0, "retrieval_rank", range(1, len(top_indexes) + 1))
    results_df.insert(1, "retrieved_index", top_indexes)
    results_df.insert(2, "similarity_score", masked_scores[top_indexes])

    return results_df


#
# Dataset Image Helpers
#

def fetch_raw_example_by_index(index, ds_train_raw, ds_test_raw, num_train):
    """
    Fetch one raw Oxford-IIIT Pet example by retrieval-corpus index.
    """

    index = int(index)

    if index < num_train:
        ds_subset = ds_train_raw.skip(index).take(1)
    else:
        ds_subset = ds_test_raw.skip(index - num_train).take(1)

    for example in ds_subset:
        return example

    raise IndexError(f"Could not fetch dataset example for index: {index}")


@st.cache_data(show_spinner=False)
def get_display_image_by_index(index):
    """
    Load one dataset image for Streamlit display.
    """

    ds_train_raw, ds_test_raw, ds_info, num_train, num_test = load_tfds_splits()

    example = fetch_raw_example_by_index(
        index=int(index),
        ds_train_raw=ds_train_raw,
        ds_test_raw=ds_test_raw,
        num_train=num_train
    )

    image = example["image"]
    image = tf.image.resize(image, IMAGE_SIZE)
    image = tf.cast(image, tf.float32) / 255.0

    return image.numpy()


def resize_image_preserve_aspect(image, max_dim=256):
    """
    Resize an image tensor while preserving aspect ratio and add a batch dimension.
    """

    shape = tf.cast(tf.shape(image)[:-1], tf.float32)
    long_dim = tf.reduce_max(shape)
    scale = max_dim / long_dim
    new_shape = tf.cast(shape * scale, tf.int32)

    image = tf.image.resize(image, new_shape)
    image = image[tf.newaxis, :]

    return image


def get_content_tensor_from_dataset_index(index, max_dim=256):
    """
    Load a dataset image as a batched content tensor for style transfer.
    """

    ds_train_raw, ds_test_raw, ds_info, num_train, num_test = load_tfds_splits()

    example = fetch_raw_example_by_index(
        index=int(index),
        ds_train_raw=ds_train_raw,
        ds_test_raw=ds_test_raw,
        num_train=num_train
    )

    image = tf.cast(example["image"], tf.float32) / 255.0

    return resize_image_preserve_aspect(image, max_dim=max_dim)


#
# Uploaded Image Helpers
#

def pil_image_to_display_array(pil_image):
    """
    Convert a PIL image to a display-ready NumPy array.
    """

    image = pil_image.convert("RGB")
    image = image.resize(IMAGE_SIZE)

    image_array = np.array(image).astype("float32") / 255.0

    return image_array


def pil_image_to_mobilenet_batch(pil_image):
    """
    Convert a PIL image to a MobileNetV2-preprocessed batch.
    """

    image = pil_image.convert("RGB")
    image = image.resize(IMAGE_SIZE)

    image_array = np.array(image).astype("float32")
    image_batch = np.expand_dims(image_array, axis=0)

    image_batch = mobilenet_preprocess_input(image_batch)

    return image_batch


def pil_image_to_content_tensor(pil_image, max_dim=256):
    """
    Convert a PIL image to a batched content tensor for style transfer.
    """

    image = pil_image.convert("RGB")
    image_array = np.array(image).astype("float32") / 255.0
    image_tensor = tf.convert_to_tensor(image_array)

    return resize_image_preserve_aspect(image_tensor, max_dim=max_dim)


def classify_image(pil_image, classifier_model, breed_names):
    """
    Predict the pet breed for an uploaded PIL image.
    """

    image_batch = pil_image_to_mobilenet_batch(pil_image)

    probabilities = classifier_model.predict(image_batch, verbose=0)[0]

    predicted_index = int(np.argmax(probabilities))
    predicted_breed = breed_names[predicted_index]
    predicted_confidence = float(probabilities[predicted_index])

    top_indexes = np.argsort(probabilities)[::-1][:5]

    top_predictions_df = pd.DataFrame(
        [
            {
                "rank": rank + 1,
                "breed": breed_names[index],
                "confidence": float(probabilities[index])
            }
            for rank, index in enumerate(top_indexes)
        ]
    )

    return predicted_index, predicted_breed, predicted_confidence, top_predictions_df


def extract_uploaded_embedding(pil_image, feature_extractor):
    """
    Extract a MobileNetV2 embedding for an uploaded PIL image.
    """

    image_batch = pil_image_to_mobilenet_batch(pil_image)
    embedding = feature_extractor.predict(image_batch, verbose=0)[0]

    return embedding


#
# Style Transfer Helpers
#

def load_style_image_from_path(image_path, max_dim=256):
    """
    Load a style image from disk as a batched tensor scaled to [0, 1].
    """

    image_bytes = tf.io.read_file(str(image_path))
    image = tf.image.decode_image(image_bytes, channels=3)
    image = tf.image.convert_image_dtype(image, tf.float32)

    return resize_image_preserve_aspect(image, max_dim=max_dim)


def tensor_to_image(image_tensor):
    """
    Convert a batched or unbatched float image tensor in [0, 1] to uint8 array.
    """

    if len(image_tensor.shape) == 4:
        image_tensor = image_tensor[0]

    image_tensor = tf.clip_by_value(image_tensor, 0.0, 1.0)
    image_array = tf.cast(image_tensor * 255.0, tf.uint8).numpy()

    return image_array


def gram_matrix(input_tensor):
    """
    Compute Gram matrix for style representation.
    """

    result = tf.linalg.einsum("bijc,bijd->bcd", input_tensor, input_tensor)

    input_shape = tf.shape(input_tensor)
    num_locations = tf.cast(input_shape[1] * input_shape[2], tf.float32)

    return result / num_locations


def vgg_layers(layer_names):
    """
    Create a VGG19 model that returns selected intermediate layer outputs.
    """

    vgg = VGG19(include_top=False, weights="imagenet")
    vgg.trainable = False

    outputs = [vgg.get_layer(name).output for name in layer_names]

    model = keras.Model([vgg.input], outputs)

    return model


class StyleContentModel(keras.models.Model):
    """
    Model that returns style and content dictionaries for an input image.
    """

    def __init__(self, style_layers, content_layers):
        super().__init__()

        self.vgg = vgg_layers(style_layers + content_layers)
        self.style_layers = style_layers
        self.content_layers = content_layers
        self.num_style_layers = len(style_layers)

        self.vgg.trainable = False

    def call(self, inputs):
        """
        Compute style and content features for the input image.
        """

        inputs = inputs * 255.0
        preprocessed_inputs = vgg_preprocess_input(inputs)

        outputs = self.vgg(preprocessed_inputs)

        style_outputs = outputs[:self.num_style_layers]
        content_outputs = outputs[self.num_style_layers:]

        style_outputs = [gram_matrix(style_output) for style_output in style_outputs]

        style_dict = {
            style_name: value
            for style_name, value in zip(self.style_layers, style_outputs)
        }

        content_dict = {
            content_name: value
            for content_name, value in zip(self.content_layers, content_outputs)
        }

        return {
            "style": style_dict,
            "content": content_dict
        }


def run_style_transfer(
    content_image,
    style_image,
    style_layers,
    content_layers,
    style_weight=1e-2,
    content_weight=1e4,
    total_variation_weight=30,
    epochs=3,
    steps_per_epoch=10,
    optimizer_lr=0.02
):
    """
    Run neural style transfer for one content/style pair.
    """

    extractor = StyleContentModel(style_layers, content_layers)

    style_targets = extractor(style_image)["style"]
    content_targets = extractor(content_image)["content"]

    num_style_layers = len(style_layers)
    num_content_layers = len(content_layers)

    def style_content_loss(outputs):
        """
        Compute combined style and content loss.
        """

        style_outputs = outputs["style"]
        style_loss = tf.add_n([
            tf.reduce_mean((style_outputs[name] - style_targets[name]) ** 2)
            for name in style_outputs.keys()
        ])
        style_loss *= style_weight / num_style_layers

        content_outputs = outputs["content"]
        content_loss = tf.add_n([
            tf.reduce_mean((content_outputs[name] - content_targets[name]) ** 2)
            for name in content_outputs.keys()
        ])
        content_loss *= content_weight / num_content_layers

        return style_loss + content_loss

    image = tf.Variable(content_image)

    optimizer = tf.keras.optimizers.Adam(
        learning_rate=optimizer_lr,
        beta_1=0.99,
        epsilon=1e-1
    )

    @tf.function()
    def train_step(image_variable):
        """
        Run one style-transfer optimization step.
        """

        with tf.GradientTape() as tape:
            outputs = extractor(image_variable)
            loss = style_content_loss(outputs)
            loss += total_variation_weight * tf.reduce_sum(
                tf.image.total_variation(image_variable)
            )

        gradients = tape.gradient(loss, image_variable)

        optimizer.apply_gradients([(gradients, image_variable)])

        image_variable.assign(tf.clip_by_value(image_variable, 0.0, 1.0))

        return loss

    progress = st.progress(0)
    status = st.empty()

    total_steps = epochs * steps_per_epoch
    step_counter = 0

    for epoch in range(epochs):
        for step in range(steps_per_epoch):
            loss_value = train_step(image)
            step_counter += 1

            progress.progress(step_counter / total_steps)
            status.write(
                f"Style transfer step {step_counter}/{total_steps} "
                f"- loss: {float(loss_value.numpy()):.4f}"
            )

    progress.empty()
    status.empty()

    return tensor_to_image(image)
